py -m pip install asgiref
py -m pip install certifi
py -m pip install charset-normalizer
py -m pip install cycler
py -m pip install DateTime
py -m pip install Django
py -m pip install django-cors-headers
py -m pip install django-cors-middleware
py -m pip install django-crispy-forms
py -m pip install djangorestframework
py -m pip install fonttools
py -m pip install idna
py -m pip install Jinja2
py -m pip install kiwisolver
py -m pip install MarkupSafe
py -m pip install matplotlib
py -m pip install numpy
py -m pip install packaging
py -m pip install pandas
py -m pip install Pillow
py -m pip install pyparsing
py -m pip install python-dateutil
py -m pip install pytz
py -m pip install requests
py -m pip install requests-cache
py -m pip install scipy
py -m pip install setuptools-scm
py -m pip install signalr-client-aio
py -m pip install six
py -m pip install sqlparse
py -m pip install thefuzz
py -m pip install timple
py -m pip install tomli
py -m pip install urllib3
py -m pip install websockets
py -m pip install zope.interface