# Generated by Django 3.0.6 on 2021-04-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210405_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasoncalendar',
            name='featureRaceDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasoncalendar',
            name='fp1Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasoncalendar',
            name='fp2Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasoncalendar',
            name='fp3Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasoncalendar',
            name='qualiDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasoncalendar',
            name='sprintRaceDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
