# Generated by Django 3.0.6 on 2021-04-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210405_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasoncalendar',
            name='qualiStartTime',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
