# Generated by Django 3.0.6 on 2021-04-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210405_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasoncalendar',
            name='year',
            field=models.IntegerField(default=2021, null=True),
        ),
    ]
