# Generated by Django 3.0.6 on 2021-04-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210405_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasoncalendar',
            name='raceRound',
            field=models.IntegerField(null=True),
        ),
    ]
