# Generated by Django 3.0.6 on 2021-04-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_seasoncalendar_raceround'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverpredictions',
            name='submittedDate',
            field=models.DateField(auto_now_add=True, max_length=255, null=True),
        ),
    ]
