# Generated by Django 3.0.6 on 2021-04-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210407_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructorseasonpredictions',
            name='sumittedDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
