# Generated by Django 3.0.6 on 2021-04-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_constructors_isongrid'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasons',
            name='numMidfieldDrivers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='seasons',
            name='numMidfieldTeams',
            field=models.IntegerField(null=True),
        ),
    ]
