# Generated by Django 3.0.6 on 2021-04-13 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210407_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circuits',
            old_name='circuitref',
            new_name='circuitRef',
        ),
    ]
