# Generated by Django 3.0.6 on 2021-04-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210413_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='races',
            old_name='date',
            new_name='calendar',
        ),
        migrations.RemoveField(
            model_name='races',
            name='calendar_round',
        ),
        migrations.RemoveField(
            model_name='races',
            name='name',
        ),
        migrations.RemoveField(
            model_name='races',
            name='url',
        ),
        migrations.AddField(
            model_name='races',
            name='isComplete',
            field=models.SmallIntegerField(default=0),
        ),
    ]
