# Generated by Django 3.0.6 on 2021-04-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210413_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasoncalendar',
            name='isComplete',
            field=models.SmallIntegerField(default=0),
        ),
    ]
