# Generated by Django 3.0.6 on 2021-04-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_seasoncalendar_iscomplete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paddocks',
            name='code',
        ),
        migrations.RemoveField(
            model_name='paddocks',
            name='name',
        ),
        migrations.AddField(
            model_name='paddocks',
            name='paddockCode',
            field=models.CharField(default=997955, max_length=6),
        ),
        migrations.AddField(
            model_name='paddocks',
            name='paddockName',
            field=models.CharField(default='paddock3233310', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='paddocks',
            name='numPlayers',
            field=models.IntegerField(default=0),
        ),
    ]
