# Generated by Django 3.0.6 on 2021-04-16 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0014_auto_20210414_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paddocks',
            name='numPlayers',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paddocks',
            name='paddockCode',
            field=models.CharField(default=918058, max_length=6),
        ),
        migrations.AlterField(
            model_name='paddocks',
            name='paddockName',
            field=models.CharField(default='paddock3510610', max_length=30, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='userPaddocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
