# Generated by Django 3.0.6 on 2021-04-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210416_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paddocks',
            name='paddockCode',
            field=models.CharField(default='938510', max_length=6),
        ),
        migrations.AlterField(
            model_name='paddocks',
            name='paddockName',
            field=models.CharField(default='paddock06080', max_length=30, null=True, unique=True),
        ),
    ]
