# Generated by Django 3.0.6 on 2021-04-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210416_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='paddocks',
            name='year',
            field=models.IntegerField(default=2021, null=True),
        ),
        migrations.AlterField(
            model_name='paddocks',
            name='paddockCode',
            field=models.CharField(default='42302', max_length=6),
        ),
        migrations.AlterField(
            model_name='paddocks',
            name='paddockName',
            field=models.CharField(default='paddock06793', max_length=30, null=True, unique=True),
        ),
    ]
