# Generated by Django 3.0.6 on 2021-04-16 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210416_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaddocks',
            name='paddock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.paddocks'),
        ),
        migrations.AlterField(
            model_name='paddocks',
            name='paddockCode',
            field=models.CharField(default='R10R2R', max_length=6),
        ),
        migrations.AlterField(
            model_name='paddocks',
            name='paddockName',
            field=models.CharField(default='paddockWU80W', max_length=30, null=True, unique=True),
        ),
    ]
