# Generated by Django 3.0.6 on 2021-04-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210416_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='paddocks',
            name='isPublic',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paddocks',
            name='paddockCode',
            field=models.CharField(default='46HWQ', max_length=6),
        ),
        migrations.AlterField(
            model_name='paddocks',
            name='paddockName',
            field=models.CharField(default='paddockHUUYY', max_length=30, null=True, unique=True),
        ),
    ]
