# Generated by Django 3.0.6 on 2021-04-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210421_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructorstandings',
            name='year',
            field=models.IntegerField(default=2021, null=True),
        ),
    ]
