# Generated by Django 3.0.6 on 2021-04-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_predictionpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionpoints',
            name='isConstructorStandingPrediction',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='predictionpoints',
            name='isDriverStandingPrediction',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='predictionpoints',
            name='isFeatureRaceMidfieldPrediction',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
