# Generated by Django 3.0.6 on 2021-04-22 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_results_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionpoints',
            name='driverPrediction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.driverPredictions'),
        ),
    ]
