# Generated by Django 3.0.6 on 2021-04-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_predictionpoints_driverprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverpredictions',
            name='year',
            field=models.IntegerField(default=2021, null=True),
        ),
    ]
