# Generated by Django 3.0.6 on 2021-04-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_driverpredictions_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverpredictions',
            name='pointsCaptured',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
