# Generated by Django 3.0.6 on 2021-04-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_driverpredictions_pointscaptured'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructorseasonpredictions',
            name='year',
            field=models.IntegerField(default=2021, null=True),
        ),
    ]
