# Generated by Django 3.0.6 on 2021-04-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_ergastrequestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasoncalendar',
            name='constructorStandingsCaptured',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='seasoncalendar',
            name='driverStandingsCaptured',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
