# Generated by Django 3.0.6 on 2021-04-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20210424_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='paddocks',
            name='currentPointsCalcRound',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
