# Generated by Django 3.0.6 on 2021-04-26 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20210426_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionpoints',
            name='constructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.constructors'),
        ),
        migrations.AddField(
            model_name='predictionpoints',
            name='constructorSeasonPrediction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.constructorSeasonPredictions'),
        ),
    ]
