# Generated by Django 3.0.6 on 2021-04-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20210426_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='isIncludedInPredcitions',
            field=models.IntegerField(null=True),
        ),
    ]
