# Generated by Django 3.0.6 on 2021-04-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_drivers_isincludedinpredcitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructors',
            name='isIncludedInPrediction',
            field=models.SmallIntegerField(null=True),
        ),
    ]
