# Generated by Django 3.0.6 on 2021-04-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20210428_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderboards',
            old_name='completedRounds',
            new_name='seasonCalendar',
        ),
        migrations.RemoveField(
            model_name='leaderboards',
            name='game',
        ),
        migrations.AddField(
            model_name='leaderboards',
            name='isConstructorStandingsGame',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='leaderboards',
            name='isDriverStangingsGame',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='leaderboards',
            name='isMidfieldGame',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='leaderboards',
            name='previousPosition',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
