# Generated by Django 3.0.6 on 2021-04-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20210428_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboards',
            name='previousPoints',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='leaderboards',
            name='roundPoints',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
