# Generated by Django 3.0.6 on 2021-04-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20210428_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderboards',
            old_name='leaderboardPosition',
            new_name='currentPosition',
        ),
        migrations.RenameField(
            model_name='leaderboards',
            old_name='previousPoints',
            new_name='currentTotalPoints',
        ),
        migrations.AddField(
            model_name='leaderboards',
            name='previousTotalPoints',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
