# Generated by Django 3.0.6 on 2021-04-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20210428_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasoncalendar',
            name='constructorStandingsBoardUpdated',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='seasoncalendar',
            name='driverStandingsLeaderBoardUpdated',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='seasoncalendar',
            name='midfieldLeaderBoardUpdated',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
