# Generated by Django 3.0.6 on 2021-04-28 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20210428_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seasoncalendar',
            old_name='constructorStandingsBoardUpdated',
            new_name='constructorStandingsleaderboardUpdated',
        ),
        migrations.RenameField(
            model_name='seasoncalendar',
            old_name='driverStandingsLeaderBoardUpdated',
            new_name='driverStandingsLeaderboardUpdated',
        ),
        migrations.RenameField(
            model_name='seasoncalendar',
            old_name='midfieldLeaderBoardUpdated',
            new_name='midfieldLeaderboardUpdated',
        ),
    ]
