# Generated by Django 3.0.6 on 2021-04-28 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20210428_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderboards',
            old_name='round_player_position',
            new_name='roundPlayerPosition',
        ),
    ]
