# Generated by Django 3.0.6 on 2021-04-30 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20210428_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='paddockMidfieldExcludedTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excludedTeam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.constructors')),
                ('paddock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.paddocks')),
            ],
        ),
    ]
