# Generated by Django 3.0.6 on 2021-05-04 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_paddockmidfieldexcludedteams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderboards',
            old_name='isDriverStangingsGame',
            new_name='isDriverStandingsGame',
        ),
    ]
