# Generated by Django 3.0.6 on 2021-05-07 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20210504_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='gameExcludedTeamsByPaddock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2021, null=True)),
                ('constructor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.constructors')),
                ('paddock_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.paddocks')),
            ],
        ),
        migrations.CreateModel(
            name='paddockMidfieldRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numDriversOnLeaderBoard', models.IntegerField(default=16, null=True)),
                ('paddock_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.paddocks')),
            ],
        ),
        migrations.RemoveField(
            model_name='racelymidfieldpredictions',
            name='game',
        ),
        migrations.RemoveField(
            model_name='seasonteampredictions',
            name='game',
        ),
        migrations.DeleteModel(
            name='games',
        ),
    ]
