# Generated by Django 3.0.6 on 2021-05-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20210507_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboards',
            name='isInPaddockMidfieldRules',
            field=models.SmallIntegerField(default=1, null=True),
        ),
    ]
