# Generated by Django 3.0.6 on 2021-05-10 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_remove_leaderboards_isinpaddockmidfieldrules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seasoncalendar',
            old_name='constructorStandingsleaderboardUpdated',
            new_name='constructorStandingsLeaderboardUpdated',
        ),
    ]
