# Generated by Django 3.0.6 on 2021-05-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20210510_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionpoints',
            name='isFinishingSinglePoint',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='predictionpoints',
            name='isPredictedSinglePoint',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
