# Generated by Django 3.0.6 on 2021-05-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_auto_20210513_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboards',
            name='currentOverallPosition',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='leaderboards',
            name='roundPlayerPosition',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
