# Generated by Django 3.0.6 on 2021-05-20 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_auto_20210514_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paddockmidfieldrules',
            old_name='paddock_id',
            new_name='paddock',
        ),
    ]
