# Generated by Django 3.0.6 on 2021-05-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20210521_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboards',
            name='isActive',
            field=models.SmallIntegerField(default=1, null=True),
        ),
    ]
