# Generated by Django 3.0.6 on 2021-05-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_leaderboards_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaddocks',
            name='isPaddockAdmin',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
