# Generated by Django 3.0.6 on 2021-05-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_userpaddocks_ispaddockadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaddocks',
            name='dateTimeJoined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
