# Generated by Django 3.0.6 on 2021-06-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_seasoncalendar_combinedstandingsleaderboardupdated'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboards',
            name='isCombinedStandingsGame',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
