# Generated by Django 3.0.6 on 2021-06-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_leaderboards_iscombinedstandingsgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='paddockpointscapturelog',
            name='isSprintCombinedPoints',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
