# Generated by Django 3.0.6 on 2021-06-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20210604_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaddocks',
            name='isPaddockSuperAdmin',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
