# Generated by Django 3.0.6 on 2021-06-09 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_paddockmanagementlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='paddockMaxUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxUsers', models.IntegerField(default=20)),
                ('createdDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('paddock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.paddocks')),
            ],
        ),
    ]
