# Generated by Django 3.0.6 on 2021-06-09 11:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0069_paddockbannedused'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='paddockBannedUsed',
            new_name='paddockBannedUsers',
        ),
    ]
