# Generated by Django 3.0.6 on 2021-08-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20210609_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverpredictions',
            name='isMidSeasonPrediction',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
