# Generated by Django 3.0.6 on 2021-08-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_constructorseasonpredictions_ismidseasonprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionpoints',
            name='isConstructorMidStandingPrediction',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='predictionpoints',
            name='isDriverMidStandingPrediction',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
