# Generated by Django 3.0.6 on 2021-08-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_auto_20210831_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='paddockpointscapturelog',
            name='isConstructorMidStandingPoints',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='paddockpointscapturelog',
            name='isDriverMidStandingPoints',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
