# Generated by Django 3.0.6 on 2021-08-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_auto_20210831_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboards',
            name='isCombinedMidStandingsGame',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='leaderboards',
            name='isConstructorMidStandingsGame',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='leaderboards',
            name='isDriverMidStandingsGame',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
