# Generated by Django 3.0.6 on 2021-09-24 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0075_auto_20210831_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='customGames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='paddockCustomGames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customGame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.customGames')),
                ('paddock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.paddocks')),
            ],
        ),
        migrations.CreateModel(
            name='jsonFileLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('year', models.IntegerField(default=2021, null=True)),
                ('isMidfieldGame', models.SmallIntegerField(default=0, null=True)),
                ('isPreSeasonDriverGame', models.SmallIntegerField(default=0, null=True)),
                ('isMidSeasonDriverGame', models.SmallIntegerField(default=0, null=True)),
                ('isPreSeasonConstuctorGame', models.SmallIntegerField(default=0, null=True)),
                ('isMidSeasonConstructorGame', models.SmallIntegerField(default=0, null=True)),
                ('isPreSeasonCombinedGame', models.SmallIntegerField(default=0, null=True)),
                ('isMidSeasonCombinedGame', models.SmallIntegerField(default=0, null=True)),
                ('isCustomGameFile', models.SmallIntegerField(default=0, null=True)),
                ('fileLocation', models.CharField(max_length=255, null=True)),
                ('customGame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.paddockCustomGames')),
                ('paddock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.paddocks')),
                ('seasonCalendar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.seasonCalendar')),
            ],
        ),
    ]
