# Generated by Django 3.0.6 on 2021-09-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_customgames_jsonfilelocations_paddockcustomgames'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonfilelocations',
            name='isGeneralLeaderboard',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
