# Generated by Django 3.0.6 on 2021-09-24 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_jsonfilelocations_isgeneralleaderboard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jsonfilelocations',
            old_name='isPreSeasonConstuctorGame',
            new_name='isPreSeasonConstructorGame',
        ),
    ]
