# Generated by Django 3.0.6 on 2021-10-06 22:22

import api.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_auto_20210924_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='paddockRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruleSetName', models.CharField(max_length=128, null=True)),
                ('numDriversOnMidfieldLeaderBoard', models.IntegerField(default=16, null=True)),
                ('preSeasonDriverPredictionDeadlineDate', models.DateField(default=datetime.date(2021, 3, 26), null=True)),
                ('preSeasonDriverPredictionDeadlineTime', models.TimeField(default=datetime.time(11, 30), null=True)),
                ('preSeasonConstructorPredictionDeadlineDate', models.DateField(default=api.models.paddockRules.getDefaultPreSeasonStartDate, null=True)),
                ('preSeasonConstructorPredictionDeadlineTime', models.TimeField(default=api.models.paddockRules.getDefaultPreSeasonStartTime, null=True)),
                ('midSeasonDriverPredictionDeadlineDate', models.DateField(default=datetime.date(2021, 9, 3), null=True)),
                ('midSeasonDriverPredictionDeadlineTime', models.TimeField(default=datetime.time(11, 30), null=True)),
                ('midSeasonConstructorPredictionDeadlineDate', models.DateField(default=api.models.paddockRules.getDefaultMidSeasonStartDate, null=True)),
                ('midSeasonConstructorPredictionDeadlineTime', models.TimeField(default=api.models.paddockRules.getDefaultMidSeasonStartTime, null=True)),
                ('midfieldDriverPredictionStartDate', models.DateField(default=datetime.date(2021, 3, 27), null=True)),
                ('midfieldDriverPredictionDeadlineSession', models.CharField(max_length=55, null=True)),
                ('year', models.IntegerField(default=2021, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='paddockMidfieldRules',
        ),
        migrations.AddField(
            model_name='paddocks',
            name='paddockRules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.paddockRules'),
        ),
    ]
