# Generated by Django 3.0.6 on 2021-10-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_auto_20211007_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paddockrules',
            name='midfieldDriverPredictionDeadlineSession',
            field=models.CharField(default='Q1/Sprint', max_length=55, null=True),
        ),
    ]
