# Generated by Django 3.0.6 on 2021-10-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_auto_20211007_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paddockmidfieldexcludedteams',
            old_name='excludedTeam',
            new_name='constructor',
        ),
        migrations.AddField(
            model_name='paddockmidfieldexcludedteams',
            name='year',
            field=models.IntegerField(default=2021, null=True),
        ),
    ]
