# Generated by Django 3.0.6 on 2021-10-18 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0082_defaultmidfieldexcludedteamsbyseason'),
    ]

    operations = [
        migrations.CreateModel(
            name='userPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isBeta', models.SmallIntegerField(default=1, null=True)),
                ('hasPaid', models.SmallIntegerField(default=0, null=True)),
                ('hasDonated', models.SmallIntegerField(default=0, null=True)),
                ('paymentAmount', models.IntegerField(null=True)),
                ('donationAmount', models.IntegerField(null=True)),
                ('donationDate', models.DateField(null=True)),
                ('paymentDate', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
