# Generated by Django 3.0.6 on 2021-10-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_userpayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayments',
            name='year',
            field=models.IntegerField(default=2021, null=True),
        ),
    ]
