# Generated by Django 3.0.6 on 2021-10-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_userpayments_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='payementPaddockRestrictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2021, null=True)),
                ('betaUserNumPublicPaddocks', models.IntegerField(null=True)),
                ('betaNumPrivatePaddocks', models.IntegerField(null=True)),
                ('freeUserNumPublicPaddocks', models.IntegerField(null=True)),
                ('freeUserNumPrivatePaddocks', models.IntegerField(null=True)),
                ('bronzeUserNumPublicPaddocks', models.IntegerField(null=True)),
                ('bronzeUserNumPrivatePaddocks', models.IntegerField(null=True)),
                ('silverUserNumPublicPaddocks', models.IntegerField(null=True)),
                ('silverUserNumPrivatePaddocks', models.IntegerField(null=True)),
                ('goldUserNumPublicPaddocks', models.IntegerField(null=True)),
                ('goldUserNumPrivatePaddocks', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userPaymentThresholds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betaAmount', models.IntegerField(null=True)),
                ('freeAmount', models.IntegerField(null=True)),
                ('bronzeAmount', models.IntegerField(null=True)),
                ('silverAmount', models.IntegerField(null=True)),
                ('goldAmount', models.IntegerField(null=True)),
                ('year', models.IntegerField(default=2021, null=True)),
            ],
        ),
    ]
