# Generated by Django 3.0.6 on 2021-10-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_auto_20211018_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaddockcount',
            name='numPrivatePaddocksCreated',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='userpaddockcount',
            name='numPublicPaddocksCreated',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
