# Generated by Django 3.0.6 on 2021-10-18 16:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0087_auto_20211018_1731'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userPayments',
            new_name='userDonations',
        ),
    ]
