# Generated by Django 3.0.6 on 2021-10-18 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_auto_20211018_1913'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='payementCreatePaddockRestrictions',
            new_name='paymentCreatePaddockRestrictions',
        ),
        migrations.RenameModel(
            old_name='payementJoinPaddockRestrictions',
            new_name='paymentJoinPaddockRestrictions',
        ),
    ]
