# Generated by Django 3.0.6 on 2021-10-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_auto_20211018_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='paddockrules',
            name='numConstructorsOnMidSeasonLeaderboard',
            field=models.IntegerField(default=20, null=True),
        ),
        migrations.AddField(
            model_name='paddockrules',
            name='numConstructorsOnPreSeasonLeaderboard',
            field=models.IntegerField(default=20, null=True),
        ),
        migrations.AddField(
            model_name='paddockrules',
            name='numDriversOnMidSeasonLeaderboard',
            field=models.IntegerField(default=20, null=True),
        ),
        migrations.AddField(
            model_name='paddockrules',
            name='numDriversOnPreSeasonLeaderboard',
            field=models.IntegerField(default=20, null=True),
        ),
    ]
