# Generated by Django 3.0.6 on 2021-10-19 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_auto_20211019_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paddockrules',
            name='numConstructorsOnMidSeasonLeaderboard',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='paddockrules',
            name='numConstructorsOnPreSeasonLeaderboard',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.CreateModel(
            name='paddockRulesExcludedTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paddock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.paddockRules')),
                ('paddockMidfieldExcludedTeams', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.paddockMidfieldExcludedTeams')),
            ],
        ),
    ]
