# Generated by Django 3.0.6 on 2021-10-19 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_auto_20211019_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='paddockmidfieldexcludedteams',
            name='paddockRule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.paddockRules'),
        ),
    ]
