# Generated by Django 3.0.6 on 2021-10-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_auto_20211019_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='paddockrulesexcludedteams',
            name='year',
            field=models.IntegerField(default=2021, null=True),
        ),
    ]
