# Generated by Django 3.0.6 on 2021-10-28 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_paddockrulesexcludedteams_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuits',
            name='flag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.flags'),
        ),
    ]
