# Generated by Django 3.0.6 on 2021-10-28 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0097_auto_20211028_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructorapinameconverstions',
            name='constructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.constructors'),
        ),
        migrations.AlterField(
            model_name='constructorresults',
            name='constructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.constructors'),
        ),
        migrations.AlterField(
            model_name='constructorresults',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.races'),
        ),
        migrations.AlterField(
            model_name='constructors',
            name='flag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.flags'),
        ),
        migrations.AlterField(
            model_name='constructorseasonpredictions',
            name='position1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constructor1Prediction', to='api.constructors'),
        ),
        migrations.AlterField(
            model_name='constructorseasonpredictions',
            name='position10',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constructor10Prediction', to='api.constructors'),
        ),
        migrations.AlterField(
            model_name='constructorseasonpredictions',
            name='position11',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constructor11Prediction', to='api.constructors'),
        ),
        migrations.AlterField(
            model_name='constructorseasonpredictions',
            name='position12',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constructor12Prediction', to='api.constructors'),
        ),
        migrations.AlterField(
            model_name='constructorseasonpredictions',
            name='position2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constructor2Prediction', to='api.constructors'),
        ),
        migrations.AlterField(
            model_name='constructorseasonpredictions',
            name='position3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constructor3Prediction', to='api.constructors'),
        ),
        migrations.AlterField(
            model_name='constructorseasonpredictions',
            name='position4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constructor4Prediction', to='api.constructors'),
        ),
        migrations.AlterField(
            model_name='constructorseasonpredictions',
            name='position5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constructor5Prediction', to='api.constructors'),
        ),
        migrations.AlterField(
            model_name='constructorseasonpredictions',
            name='position6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constructor6Prediction', to='api.constructors'),
        ),
        migrations.AlterField(
            model_name='constructorseasonpredictions',
            name='position7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constructor7Prediction', to='api.constructors'),
        ),
        migrations.AlterField(
            model_name='constructorseasonpredictions',
            name='position8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constructor8Prediction', to='api.constructors'),
        ),
        migrations.AlterField(
            model_name='constructorseasonpredictions',
            name='position9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constructor9Prediction', to='api.constructors'),
        ),
        migrations.AlterField(
            model_name='constructorstandings',
            name='constructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.constructors'),
        ),
        migrations.AlterField(
            model_name='constructorstandings',
            name='seasonCalendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.seasonCalendar'),
        ),
        migrations.AlterField(
            model_name='customgames',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='defaultmidfieldexcludedteamsbyseason',
            name='constructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.constructors'),
        ),
        migrations.AlterField(
            model_name='driverpredictions',
            name='position1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver1Prediction', to='api.drivers'),
        ),
        migrations.AlterField(
            model_name='driverpredictions',
            name='position10',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver10Prediction', to='api.drivers'),
        ),
        migrations.AlterField(
            model_name='driverpredictions',
            name='position11',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver11Prediction', to='api.drivers'),
        ),
        migrations.AlterField(
            model_name='driverpredictions',
            name='position12',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver12Prediction', to='api.drivers'),
        ),
        migrations.AlterField(
            model_name='driverpredictions',
            name='position13',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver13Prediction', to='api.drivers'),
        ),
        migrations.AlterField(
            model_name='driverpredictions',
            name='position14',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver14Prediction', to='api.drivers'),
        ),
        migrations.AlterField(
            model_name='driverpredictions',
            name='position15',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver15Prediction', to='api.drivers'),
        ),
        migrations.AlterField(
            model_name='driverpredictions',
            name='position16',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver16Prediction', to='api.drivers'),
        ),
        migrations.AlterField(
            model_name='driverpredictions',
            name='position17',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver17Prediction', to='api.drivers'),
        ),
        migrations.AlterField(
            model_name='driverpredictions',
            name='position18',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver18Prediction', to='api.drivers'),
        ),
        migrations.AlterField(
            model_name='driverpredictions',
            name='position19',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver19Prediction', to='api.drivers'),
        ),
        migrations.AlterField(
            model_name='driverpredictions',
            name='position2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver2Prediction', to='api.drivers'),
        ),
        migrations.AlterField(
            model_name='driverpredictions',
            name='position20',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver20Prediction', to='api.drivers'),
        ),
        migrations.AlterField(
            model_name='driverpredictions',
            name='position21',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver21Prediction', to='api.drivers'),
        ),
        migrations.AlterField(
            model_name='driverpredictions',
            name='position22',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver22Prediction', to='api.drivers'),
        ),
        migrations.AlterField(
            model_name='driverpredictions',
            name='position3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver3Prediction', to='api.drivers'),
        ),
        migrations.AlterField(
            model_name='driverpredictions',
            name='position4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver4Prediction', to='api.drivers'),
        ),
        migrations.AlterField(
            model_name='driverpredictions',
            name='position5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver5Prediction', to='api.drivers'),
        ),
        migrations.AlterField(
            model_name='driverpredictions',
            name='position6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver6Prediction', to='api.drivers'),
        ),
        migrations.AlterField(
            model_name='driverpredictions',
            name='position7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver7Prediction', to='api.drivers'),
        ),
        migrations.AlterField(
            model_name='driverpredictions',
            name='position8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver8Prediction', to='api.drivers'),
        ),
        migrations.AlterField(
            model_name='driverpredictions',
            name='position9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver9Prediction', to='api.drivers'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='flag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.flags'),
        ),
        migrations.AlterField(
            model_name='driverstandings',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.drivers'),
        ),
        migrations.AlterField(
            model_name='driverstandings',
            name='seasonCalendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.seasonCalendar'),
        ),
        migrations.AlterField(
            model_name='ergastrequestlog',
            name='seasonCalendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.seasonCalendar'),
        ),
        migrations.AlterField(
            model_name='gameexcludedteamsbypaddock',
            name='constructor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.constructors'),
        ),
        migrations.AlterField(
            model_name='gameexcludedteamsbypaddock',
            name='paddock_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paddocks'),
        ),
        migrations.AlterField(
            model_name='jsonfilelocations',
            name='customGame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paddockCustomGames'),
        ),
        migrations.AlterField(
            model_name='jsonfilelocations',
            name='paddock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paddocks'),
        ),
        migrations.AlterField(
            model_name='jsonfilelocations',
            name='seasonCalendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.seasonCalendar'),
        ),
        migrations.AlterField(
            model_name='leaderboards',
            name='paddock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paddocks'),
        ),
        migrations.AlterField(
            model_name='leaderboards',
            name='seasonCalendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.seasonCalendar'),
        ),
        migrations.AlterField(
            model_name='leaderboards',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paddockbannedusers',
            name='bannedUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paddockbannedusers',
            name='paddock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paddocks'),
        ),
        migrations.AlterField(
            model_name='paddockcustomgames',
            name='customGame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.customGames'),
        ),
        migrations.AlterField(
            model_name='paddockcustomgames',
            name='paddock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paddocks'),
        ),
        migrations.AlterField(
            model_name='paddockmanagementlog',
            name='affectedUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affectedUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paddockmanagementlog',
            name='executingUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executingUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paddockmanagementlog',
            name='paddock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paddocks'),
        ),
        migrations.AlterField(
            model_name='paddockmaxusers',
            name='paddock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paddocks'),
        ),
        migrations.AlterField(
            model_name='paddockmidfieldexcludedteams',
            name='constructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.constructors'),
        ),
        migrations.AlterField(
            model_name='paddockmidfieldexcludedteams',
            name='paddock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paddocks'),
        ),
        migrations.AlterField(
            model_name='paddockmidfieldexcludedteams',
            name='paddockRule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paddockRules'),
        ),
        migrations.AlterField(
            model_name='paddockpointscapturelog',
            name='paddock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paddocks'),
        ),
        migrations.AlterField(
            model_name='paddockpointscapturelog',
            name='seasonCalendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.seasonCalendar'),
        ),
        migrations.AlterField(
            model_name='paddockrulesexcludedteams',
            name='paddockMidfieldExcludedTeams',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paddockMidfieldExcludedTeams'),
        ),
        migrations.AlterField(
            model_name='paddockrulesexcludedteams',
            name='paddockRules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paddockRules'),
        ),
        migrations.AlterField(
            model_name='paddocks',
            name='paddockRules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paddockRules'),
        ),
        migrations.AlterField(
            model_name='predictionpoints',
            name='constructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.constructors'),
        ),
        migrations.AlterField(
            model_name='predictionpoints',
            name='constructorSeasonPrediction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.constructorSeasonPredictions'),
        ),
        migrations.AlterField(
            model_name='predictionpoints',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.drivers'),
        ),
        migrations.AlterField(
            model_name='predictionpoints',
            name='driverPrediction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.driverPredictions'),
        ),
        migrations.AlterField(
            model_name='predictionpoints',
            name='seasonCalendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.seasonCalendar'),
        ),
        migrations.AlterField(
            model_name='predictionpoints',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qualifying',
            name='constructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.constructors'),
        ),
        migrations.AlterField(
            model_name='qualifying',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualifyingDate', to='api.seasonCalendar'),
        ),
        migrations.AlterField(
            model_name='qualifying',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.drivers'),
        ),
        migrations.AlterField(
            model_name='qualifying',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.races'),
        ),
        migrations.AlterField(
            model_name='qualifying',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualifyingStartTime', to='api.seasonCalendar'),
        ),
        migrations.AlterField(
            model_name='racelymidfieldpredictions',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.drivers'),
        ),
        migrations.AlterField(
            model_name='racelymidfieldpredictions',
            name='paddock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paddocks'),
        ),
        migrations.AlterField(
            model_name='racelymidfieldpredictions',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.results'),
        ),
        migrations.AlterField(
            model_name='racelymidfieldpredictions',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='races',
            name='calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.seasonCalendar'),
        ),
        migrations.AlterField(
            model_name='races',
            name='circuit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.circuits'),
        ),
        migrations.AlterField(
            model_name='results',
            name='constructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.constructors'),
        ),
        migrations.AlterField(
            model_name='results',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.drivers'),
        ),
        migrations.AlterField(
            model_name='results',
            name='seasonCalendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.seasonCalendar'),
        ),
        migrations.AlterField(
            model_name='seasoncalendar',
            name='circuit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.circuits'),
        ),
        migrations.AlterField(
            model_name='seasonteampredictions',
            name='constructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.drivers'),
        ),
        migrations.AlterField(
            model_name='seasonteampredictions',
            name='paddock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paddocks'),
        ),
        migrations.AlterField(
            model_name='seasonteampredictions',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.results'),
        ),
        migrations.AlterField(
            model_name='seasonteampredictions',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpaddockcount',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpaddocks',
            name='paddock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paddocks'),
        ),
        migrations.AlterField(
            model_name='userpaddocks',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
