# Generated by Django 3.0.6 on 2021-10-28 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0098_auto_20211028_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paddockmaxusers',
            name='maxUsers',
        ),
        migrations.AddField(
            model_name='paddockmaxusers',
            name='year',
            field=models.IntegerField(default=2021, null=True),
        ),
        migrations.AddField(
            model_name='paddocks',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
