# Generated by Django 3.0.6 on 2021-10-28 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_auto_20211028_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paddockmaxusers',
            name='paddock',
        ),
        migrations.AddField(
            model_name='paddocks',
            name='paddockMaxUsers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paddockMaxUsers'),
        ),
    ]
