# Generated by Django 3.0.6 on 2021-10-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_auto_20211028_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='donationAmount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='paymentAmount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
