# Generated by Django 3.0.6 on 2021-10-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_auto_20211028_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaddocks',
            name='year',
            field=models.IntegerField(default=2021, null=True),
        ),
    ]
