# Generated by Django 3.0.6 on 2021-11-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_auto_20211028_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='paddockrules',
            name='midSeasonConstructorStandingDeadlineSession',
            field=models.CharField(default='FP1', max_length=255),
        ),
        migrations.AddField(
            model_name='paddockrules',
            name='midSeasonDriverStandingDeadlineSession',
            field=models.CharField(default='FP1', max_length=255),
        ),
        migrations.AddField(
            model_name='paddockrules',
            name='preSeasonConstructorStandingDeadlineSession',
            field=models.CharField(default='FP1', max_length=255),
        ),
        migrations.AddField(
            model_name='paddockrules',
            name='preSeasonDriverStandingDeadlineSession',
            field=models.CharField(default='FP1', max_length=255),
        ),
    ]
