# Generated by Django 3.0.6 on 2021-11-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_auto_20211111_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paddocks',
            old_name='created_by',
            new_name='createdBy',
        ),
    ]
