# Generated by Django 3.0.6 on 2021-11-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_auto_20211111_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameexcludedteamsbypaddock',
            old_name='constructor_id',
            new_name='constructor',
        ),
        migrations.RenameField(
            model_name='gameexcludedteamsbypaddock',
            old_name='paddock_id',
            new_name='paddock',
        ),
    ]
