# Generated by Django 3.0.6 on 2021-11-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_auto_20211115_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paddocks',
            name='paddockUserStatusMaxUsers',
            field=models.IntegerField(default=20, null=True),
        ),
    ]
