# Generated by Django 3.0.6 on 2021-11-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_auto_20211116_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='ruleSetEcludedContructors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2021, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='status',
        ),
    ]
