# Generated by Django 3.0.6 on 2021-11-17 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_auto_20211117_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulesetecludedcontructors',
            name='constructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.constructors'),
        ),
        migrations.AddField(
            model_name='rulesetecludedcontructors',
            name='paddockRule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paddockRules'),
        ),
    ]
