# Generated by Django 3.0.6 on 2021-11-17 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_auto_20211117_2301'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ruleSetEcludedContructors',
            new_name='ruleSetExcludedContructors',
        ),
    ]
