# Generated by Django 3.0.6 on 2021-11-17 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_auto_20211117_2310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ruleSetExcludedContructors',
            new_name='ruleSetExcludedConstructors',
        ),
    ]
