# Generated by Django 3.0.6 on 2021-11-18 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_auto_20211117_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsonfilelocations',
            name='customGame',
        ),
        migrations.DeleteModel(
            name='paddockCustomGames',
        ),
    ]
