# Generated by Django 3.0.6 on 2021-11-18 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_auto_20211118_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paddockrules',
            name='paddockRulesStartRounds',
        ),
    ]
