# Generated by Django 3.0.6 on 2021-11-18 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_remove_paddockrules_paddockrulesstartrounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='paddockrulesstartrounds',
            name='paddockRules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paddockRules'),
        ),
    ]
