# Generated by Django 3.0.6 on 2021-11-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_paddockrulesstartrounds_paddockrules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paddockrules',
            name='midfieldDriverPredictionDeadlineSession',
        ),
    ]
