# Generated by Django 3.0.6 on 2021-11-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_paddockrules_midfielddriverpredictiondeadlinesession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paddockrules',
            name='midfieldDriverPredictionDeadlineSession',
        ),
    ]
