# Generated by Django 3.0.6 on 2021-11-20 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_paddockrules_midfielddriverpredictiondeadlinetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paddockrules',
            name='midfieldDriverPredictionDeadlineTime',
        ),
    ]
