# Generated by Django 3.0.6 on 2021-11-20 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0126_remove_paddockrules_midfielddriverpredictiondeadlinetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='paddockrules',
            name='midfieldDriverPredictionDeadlineTime',
            field=models.CharField(default=datetime.time(15, 0), max_length=55, null=True),
        ),
    ]
