# Generated by Django 3.0.6 on 2021-11-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_paddockrules_midfielddriverpredictiondeadlinetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='paddocks',
            name='isActive',
            field=models.SmallIntegerField(default=1, null=True),
        ),
    ]
