# Generated by Django 3.2.9 on 2022-03-15 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0128_paddocks_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructorseasonpredictions',
            name='year',
            field=models.IntegerField(default=2022, null=True),
        ),
        migrations.AlterField(
            model_name='constructorstandings',
            name='year',
            field=models.IntegerField(default=2022, null=True),
        ),
        migrations.AlterField(
            model_name='defaultmidfieldexcludedteamsbyseason',
            name='year',
            field=models.IntegerField(default=2022, null=True),
        ),
        migrations.AlterField(
            model_name='driverpredictions',
            name='year',
            field=models.IntegerField(default=2022, null=True),
        ),
        migrations.AlterField(
            model_name='driverstandings',
            name='year',
            field=models.IntegerField(default=2022, null=True),
        ),
        migrations.AlterField(
            model_name='ergastrequestlog',
            name='year',
            field=models.IntegerField(default=2022, null=True),
        ),
        migrations.AlterField(
            model_name='jsonfilelocations',
            name='year',
            field=models.IntegerField(default=2022, null=True),
        ),
        migrations.AlterField(
            model_name='paddockmanagementlog',
            name='year',
            field=models.IntegerField(default=2022, null=True),
        ),
        migrations.AlterField(
            model_name='paddockmidfieldexcludedteams',
            name='year',
            field=models.IntegerField(default=2022, null=True),
        ),
        migrations.AlterField(
            model_name='paddockrules',
            name='midSeasonDriverPredictionDeadlineDate',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='paddockrules',
            name='midSeasonDriverPredictionDeadlineTime',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='paddockrules',
            name='midfieldDriverPredictionDeadlineTime',
            field=models.CharField(default=datetime.time(17, 0), max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='paddockrules',
            name='midfieldDriverPredictionStartDate',
            field=models.DateField(default=datetime.date(2022, 3, 19), null=True),
        ),
        migrations.AlterField(
            model_name='paddockrules',
            name='numDriversOnMidfieldLeaderBoard',
            field=models.IntegerField(default=20, null=True),
        ),
        migrations.AlterField(
            model_name='paddockrules',
            name='preSeasonDriverPredictionDeadlineDate',
            field=models.DateField(default=datetime.date(2022, 3, 18), null=True),
        ),
        migrations.AlterField(
            model_name='paddockrules',
            name='preSeasonDriverPredictionDeadlineTime',
            field=models.TimeField(default=datetime.time(14, 0), null=True),
        ),
        migrations.AlterField(
            model_name='paddockrules',
            name='year',
            field=models.IntegerField(default=2022, null=True),
        ),
        migrations.AlterField(
            model_name='paddockrulesstartrounds',
            name='year',
            field=models.IntegerField(default=2022, null=True),
        ),
        migrations.AlterField(
            model_name='paddocks',
            name='paddockName',
            field=models.CharField(default='paddock', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='paddocks',
            name='year',
            field=models.IntegerField(default=2022, null=True),
        ),
        migrations.AlterField(
            model_name='paddockuserstatusmaxusers',
            name='year',
            field=models.IntegerField(default=2022, null=True),
        ),
        migrations.AlterField(
            model_name='paymentcreatepaddockrestrictions',
            name='year',
            field=models.IntegerField(default=2022, null=True),
        ),
        migrations.AlterField(
            model_name='paymentjoinpaddockrestrictions',
            name='year',
            field=models.IntegerField(default=2022, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='year',
            field=models.IntegerField(default=2022, null=True),
        ),
        migrations.AlterField(
            model_name='rulesetexcludedconstructors',
            name='year',
            field=models.IntegerField(default=2022, null=True),
        ),
        migrations.AlterField(
            model_name='seasoncalendar',
            name='year',
            field=models.IntegerField(default=2022, null=True),
        ),
        migrations.AlterField(
            model_name='userpaddockcount',
            name='year',
            field=models.IntegerField(default=2022, null=True),
        ),
        migrations.AlterField(
            model_name='userpaddocks',
            name='year',
            field=models.IntegerField(default=2022, null=True),
        ),
        migrations.AlterField(
            model_name='userpaymentthresholds',
            name='year',
            field=models.IntegerField(default=2022, null=True),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='year',
            field=models.IntegerField(default=2022, null=True),
        ),
    ]
