# Generated by Django 3.2.9 on 2022-03-24 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_auto_20220315_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='paddockSeasonPredictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isConstructorPrediction', models.SmallIntegerField(default=0, null=True)),
                ('isDriverPrediction', models.SmallIntegerField(default=0, null=True)),
                ('constructorPrediction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.constructorseasonpredictions')),
                ('driverPredicton', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.driverpredictions')),
                ('paddock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paddocks')),
            ],
        ),
    ]
