# Generated by Django 3.2.9 on 2022-03-24 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0132_paddockseasonpredictions_startround'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paddockseasonpredictions',
            old_name='StartRound',
            new_name='paddockRulesStartRound',
        ),
    ]
