# Generated by Django 3.2.9 on 2022-03-24 17:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0133_rename_startround_paddockseasonpredictions_paddockrulesstartround'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='paddockSeasonPredictions',
            new_name='paddockSeasonPredictionStartRounds',
        ),
    ]
