# Generated by Django 3.2.9 on 2022-03-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0134_rename_paddockseasonpredictions_paddockseasonpredictionstartrounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='paddockseasonpredictionstartrounds',
            name='isMidSeasonConstructorPrediction',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='paddockseasonpredictionstartrounds',
            name='isMidSeasonDriverPrediction',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
