# Generated by Django 3.2.9 on 2022-03-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0135_auto_20220324_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paddockseasonpredictionstartrounds',
            name='paddockRulesStartRound',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
