# Generated by Django 3.2.9 on 2022-03-24 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0136_alter_paddockseasonpredictionstartrounds_paddockrulesstartround'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paddockseasonpredictionstartrounds',
            old_name='driverPredicton',
            new_name='driverPrediction',
        ),
    ]
