# Generated by Django 3.2.9 on 2022-04-11 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0140_polefasteslappredictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionpoints',
            name='paddock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paddocks'),
        ),
    ]
