# Generated by Django 3.2.9 on 2022-04-12 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0141_predictionpoints_paddock'),
    ]

    operations = [
        migrations.CreateModel(
            name='predictionPointsSysyems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predictionOutBy', models.IntegerField(null=True)),
                ('pointsForPrediction', models.IntegerField(null=True)),
                ('paddockRules', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paddockrules')),
            ],
        ),
    ]
