# Generated by Django 3.2.9 on 2022-04-12 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0142_predictionpointssysyems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='predictionPointsSysyems',
            new_name='predictionPointsSysems',
        ),
    ]
