# Generated by Django 3.2.9 on 2022-04-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0145_auto_20220412_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionpoints',
            name='isFinishingDoublePoint',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='predictionpoints',
            name='isPredictedDoublePoint',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
