# Generated by Django 3.2.9 on 2022-04-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0146_auto_20220412_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionpoints',
            name='maxPoints',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
