# Generated by Django 3.2.9 on 2022-04-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0148_singlelinepredictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionpoints',
            name='resultFinishingPosition',
            field=models.IntegerField(null=True),
        ),
    ]
