# Generated by Django 3.2.9 on 2022-04-19 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0150_leaderboardsinglelinepredictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardsinglelinepredictions',
            name='finishingPosition',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='leaderboardsinglelinepredictions',
            name='isMidSeasonConstructorPrediction',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='leaderboardsinglelinepredictions',
            name='isMidSeasonDriverPrediction',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='leaderboardsinglelinepredictions',
            name='isPreSeasonConstructorPrediction',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='leaderboardsinglelinepredictions',
            name='isPreSeasonDriverPrediction',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='leaderboardsinglelinepredictions',
            name='isRacelyPrediction',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paddockrules',
            name='midSeasonDriverPredictionDeadlineDate',
            field=models.DateField(default=datetime.date(2022, 7, 29), null=True),
        ),
        migrations.AlterField(
            model_name='paddockrules',
            name='midSeasonDriverPredictionDeadlineTime',
            field=models.TimeField(default=datetime.time(14, 0), null=True),
        ),
    ]
