# Generated by Django 3.2.9 on 2022-04-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0151_auto_20220420_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionpoints',
            name='isFastestLapPoint',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='predictionpoints',
            name='isPoleSitterPoint',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
