# Generated by Django 3.2.9 on 2022-04-19 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0152_auto_20220420_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='polefasteslappredictions',
            name='resultDriver_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultDriver_id', to='api.drivers'),
        ),
    ]
