# Generated by Django 3.2.9 on 2022-04-20 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0154_auto_20220420_0134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='leaderboardSingleLinePredictions',
        ),
    ]
