# Generated by Django 3.2.9 on 2022-04-20 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0155_delete_leaderboardsinglelinepredictions'),
    ]

    operations = [
        migrations.CreateModel(
            name='leaderboardSingleLinePredictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predictedPosition', models.IntegerField(null=True)),
                ('finishingPosition', models.IntegerField(null=True)),
                ('isRacelyPrediction', models.SmallIntegerField(default=0, null=True)),
                ('isPreSeasonConstructorPrediction', models.SmallIntegerField(default=0, null=True)),
                ('isMidSeasonConstructorPrediction', models.SmallIntegerField(default=0, null=True)),
                ('isPreSeasonDriverPrediction', models.SmallIntegerField(default=0, null=True)),
                ('isMidSeasonDriverPrediction', models.SmallIntegerField(default=0, null=True)),
                ('constructorPrediction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.constructorseasonpredictions')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.drivers')),
                ('driverPrediction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.driverpredictions')),
                ('paddock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paddocks')),
                ('seasonCalendar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.seasoncalendar')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
