# Generated by Django 3.2.9 on 2022-04-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0162_rename_driverseasoncaldendarsubs_driverseasoncalendarsubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverseasoncalendarsubs',
            name='isPremanantSub',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='driverseasoncalendarsubs',
            name='year',
            field=models.IntegerField(default=2022, null=True),
        ),
    ]
