# Generated by Django 3.2.9 on 2022-04-25 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0163_auto_20220425_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverseasoncalendarsubs',
            name='subbedFromConstructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.constructors'),
        ),
    ]
