# Generated by Django 3.2.9 on 2022-04-26 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0167_auto_20220426_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='subbedInFor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subbedFor', to='api.drivers'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='seatDrivenBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subbedBy', to='api.drivers'),
        ),
    ]
