# Generated by Django 3.2.9 on 2022-04-26 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0168_auto_20220426_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constructors',
            old_name='isIncludedInPrediction',
            new_name='isIncludedInPredictions',
        ),
    ]
