# Generated by Django 3.2.9 on 2022-04-26 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0169_rename_isincludedinprediction_constructors_isincludedinpredictions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverseasoncalendarsubs',
            old_name='isPremanantSub',
            new_name='isPermanantSub',
        ),
    ]
