# Generated by Django 3.2.9 on 2022-04-26 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0171_rename_ispermanantsub_driverseasoncalendarsubs_ispermanentsub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverseasoncalendarsubs',
            name='subbedFromConstructor',
        ),
        migrations.RemoveField(
            model_name='driverseasoncalendarsubs',
            name='subbedToConstructor',
        ),
        migrations.AddField(
            model_name='driverseasoncalendarsubs',
            name='incomingDriverFromConstructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomingDriverFromConstructor', to='api.constructors'),
        ),
        migrations.AddField(
            model_name='driverseasoncalendarsubs',
            name='incomingDriverToConstructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomingDriverToConstructor', to='api.constructors'),
        ),
        migrations.AddField(
            model_name='driverseasoncalendarsubs',
            name='outgoingDriverFromConstructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoingDriverToConstructor', to='api.constructors'),
        ),
        migrations.AddField(
            model_name='driverseasoncalendarsubs',
            name='outgoingDriverToConstructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoingDriverFromConstructor', to='api.constructors'),
        ),
    ]
