# Generated by Django 3.2.9 on 2022-04-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0173_auto_20220427_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionpoints',
            name='subbbedOutDriverCode',
            field=models.CharField(default=None, max_length=8, null=True),
        ),
    ]
