# Generated by Django 3.2.9 on 2022-04-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0174_predictionpoints_subbbedoutdrivercode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictionpoints',
            old_name='subbbedOutDriverCode',
            new_name='subbedOutDriverCode',
        ),
    ]
