# Generated by Django 3.2.9 on 2022-05-02 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0175_rename_subbbedoutdrivercode_predictionpoints_subbedoutdrivercode'),
    ]

    operations = [
        migrations.CreateModel(
            name='paddockDrivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=255, null=True)),
                ('surname', models.CharField(max_length=255, null=True)),
                ('number', models.IntegerField(null=True)),
                ('code', models.CharField(max_length=3, null=True)),
                ('isOnGrid', models.SmallIntegerField(null=True)),
                ('isIncludedInPredictions', models.IntegerField(null=True)),
                ('nationality', models.CharField(default='International', max_length=255, null=True)),
                ('thumbImgLocation', models.CharField(max_length=255, null=True)),
                ('driverRef', models.CharField(max_length=255, null=True)),
                ('currentTeam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.constructors')),
                ('flag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.flags')),
                ('paddock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paddocks')),
                ('seatDrivenBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subbedBy', to='api.paddockdrivers')),
                ('subbedByUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subbedInFor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subbedFor', to='api.paddockdrivers')),
            ],
        ),
    ]
