# Generated by Django 3.2.9 on 2022-05-02 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0177_constructors_constructoriconcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='paddockdrivers',
            name='isPaddockCreatedriver',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='paddockdrivers',
            name='seasonCalendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.seasoncalendar'),
        ),
    ]
