# Generated by Django 3.2.9 on 2022-05-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0179_systemmoderators'),
    ]

    operations = [
        migrations.AddField(
            model_name='paddockdrivers',
            name='user',
            field=models.CharField(default='Kcaper', max_length=255, null=True),
        ),
    ]
