# Generated by Django 3.2.9 on 2022-05-02 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0180_paddockdrivers_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paddockdrivers',
            old_name='isPaddockCreatedriver',
            new_name='isPaddockCreatedDriver',
        ),
    ]
