# Generated by Django 3.2.9 on 2022-05-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0182_paddockdrivers_lastresultposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='paddockdrivers',
            name='hasFastestLapResult',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='paddockdrivers',
            name='hasPoleResult',
            field=models.SmallIntegerField(null=True),
        ),
    ]
