# Generated by Django 3.2.9 on 2022-05-02 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0183_auto_20220502_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='manualPaddockPoleAndFastLapRstults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdBy', models.CharField(default='Kcaper', max_length=255, null=True)),
                ('fastestLapDriver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fastesrLapDriver', to='api.paddockdrivers')),
                ('paddock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paddocks')),
                ('polePostionDriver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poleLapDriver', to='api.paddockdrivers')),
                ('seasonCalendar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.seasoncalendar')),
            ],
        ),
    ]
