# Generated by Django 3.2.9 on 2022-05-02 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0184_manualpaddockpoleandfastlaprstults'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='manualPaddockPoleAndFastLapRstults',
            new_name='manualPaddockPoleAndFastLapResults',
        ),
    ]
