# Generated by Django 3.2.9 on 2022-05-02 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0185_rename_manualpaddockpoleandfastlaprstults_manualpaddockpoleandfastlapresults'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manualpaddockpoleandfastlapresults',
            old_name='polePostionDriver',
            new_name='polePositionDriver',
        ),
    ]
