# Generated by Django 3.2.9 on 2022-05-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0186_rename_polepostiondriver_manualpaddockpoleandfastlapresults_polepositiondriver'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualpaddockpoleandfastlapresults',
            name='isFastestLapResult',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='manualpaddockpoleandfastlapresults',
            name='isPoleLapResult',
            field=models.SmallIntegerField(null=True),
        ),
    ]
