# Generated by Django 3.2.9 on 2022-05-08 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0187_auto_20220503_2041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='manualRestult',
            new_name='manualResult',
        ),
    ]
