# Generated by Django 3.2.9 on 2022-05-08 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0188_rename_manualrestult_manualresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualresultlog',
            name='seasonCalendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.seasoncalendar'),
        ),
    ]
