# Generated by Django 3.2.9 on 2022-05-10 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0189_manualresultlog_seasoncalendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='manualPredictionPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPoleSitterPoint', models.SmallIntegerField(default=0, null=True)),
                ('isFastestLapPoint', models.SmallIntegerField(default=0, null=True)),
                ('predictedPosition', models.IntegerField(null=True)),
                ('finishingPosition', models.IntegerField(default=100, null=True)),
                ('resultFinishingPosition', models.IntegerField(null=True)),
                ('pointsForPrediction', models.IntegerField(default=0, null=True)),
                ('isFeatureRaceMidfieldPrediction', models.SmallIntegerField(default=0, null=True)),
                ('isDriverStandingPrediction', models.SmallIntegerField(default=0, null=True)),
                ('isDriverMidStandingPrediction', models.SmallIntegerField(default=0, null=True)),
                ('isConstructorStandingPrediction', models.SmallIntegerField(default=0, null=True)),
                ('isConstructorMidStandingPrediction', models.SmallIntegerField(default=0, null=True)),
                ('isFinishingSinglePoint', models.SmallIntegerField(default=0, null=True)),
                ('isPredictedSinglePoint', models.SmallIntegerField(default=0, null=True)),
                ('isFinishingDoublePoint', models.SmallIntegerField(default=0, null=True)),
                ('isPredictedDoublePoint', models.SmallIntegerField(default=0, null=True)),
                ('maxPoints', models.SmallIntegerField(default=0, null=True)),
                ('subbedOutDriverCode', models.CharField(default=None, max_length=8, null=True)),
                ('constructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.constructors')),
                ('constructorSeasonPrediction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.constructorseasonpredictions')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.drivers')),
                ('driverPrediction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.driverpredictions')),
                ('paddock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paddocks')),
                ('seasonCalendar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.seasoncalendar')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
