# Generated by Django 3.2.9 on 2022-05-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0190_manualpredictionpoints'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='manualResult',
            new_name='manualResults',
        ),
    ]
