# Generated by Django 3.2.9 on 2022-05-10 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0191_rename_manualresult_manualresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoryDriverResultPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('position', models.IntegerField(null=True)),
                ('pointsForPosition', models.IntegerField(null=True)),
                ('pointsForPolePosition', models.IntegerField(null=True)),
                ('pointsForFastestLap', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='manualResultleaderboards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isMidfieldGame', models.SmallIntegerField(default=0, null=True)),
                ('isDriverStandingsGame', models.SmallIntegerField(default=0, null=True)),
                ('isConstructorStandingsGame', models.SmallIntegerField(default=0, null=True)),
                ('isCombinedStandingsGame', models.SmallIntegerField(default=0, null=True)),
                ('isDriverMidStandingsGame', models.SmallIntegerField(default=0, null=True)),
                ('isConstructorMidStandingsGame', models.SmallIntegerField(default=0, null=True)),
                ('isCombinedMidStandingsGame', models.SmallIntegerField(default=0, null=True)),
                ('currentOverallPosition', models.IntegerField(default=1, null=True)),
                ('previousPosition', models.IntegerField(default=1, null=True)),
                ('previousTotalPoints', models.IntegerField(default=0, null=True)),
                ('currentTotalPoints', models.IntegerField(default=0, null=True)),
                ('roundPoints', models.IntegerField(default=0, null=True)),
                ('paddockDelta', models.IntegerField(null=True)),
                ('roundPlayerPosition', models.IntegerField(default=1, null=True)),
                ('isActive', models.SmallIntegerField(default=1, null=True)),
                ('paddock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paddocks')),
                ('seasonCalendar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.seasoncalendar')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
