# Generated by Django 3.2.9 on 2022-05-10 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0193_alter_manualpredictionpoints_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualresults',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paddockdrivers'),
        ),
    ]
