# Generated by Django 3.2.9 on 2022-05-27 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0197_leaderboardmanualsinglelinepredictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualresultlog',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
