# Generated by Django 3.2.9 on 2022-05-27 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0198_manualresultlog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualresultlog',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 0, 18, 28, 115307)),
        ),
    ]
