# Generated by Django 3.2.9 on 2022-05-27 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0199_alter_manualresultlog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualresultlog',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 2, 25, 32, 985004)),
        ),
    ]
